site: avinashbhat
url: "https://avinashbhat.github.io"
title: Avinash Bhat
description: 
markdown: kramdown
twitter:
  username: aviinashbhat
  card: summary
  creator: aviinashbhat
permalink: pretty

baseurl: ""

highlighter: rouge

exclude:
  - .jekyll-cache
  - node_modules
  - vendor
  - Gemfile
  - Gemfile.lock
  - README.md

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [development]
  blanklines: false
  profile: false
  startings: []

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap  

collections:
  pages:
    output: true
    permalink: /:name
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"