# Setup
title:               avinashbhat
tagline:             ''
description:         ''
url:                 http://lanyon.getpoole.com
baseurl:             ''
permalink:           pretty

# About/contact
author:
  name:              Avinash Bhat
  url:               https://twitter.com/this_is_avii
  email:             avinashbhatneelavar@gmail.com