- title: "Program Committee"
  content: "IUI - [2026](https://iui.acm.org/2026/)"

- title: "Peer Reviewing"
  content: "**Workshops**; DL4C Workshop - [2023](https://dl4c.github.io/); In2Writing Workshop - 2024, 2025; SMASH - [2025](https://smashcon.org/en/); **Conferences**; C&C - [2025](https://cc.acm.org/2025/); UIST - [2025](https://uist.acm.org/2025/); DIS - [2025](https://dis.acm.org/2025/); CHI - [2024](https://chi2024.acm.org/), [2025](https://chi2025.acm.org/), [2026](https://chi2026.acm.org/); ICSE - [2026 (As part of Shadow PC Program)](https://conf.researchr.org/track/icse-2026/icse-2026-shadow-research-track-program-committee); **Journal**; [Springer Automated Software Engineering](https://link.springer.com/journal/10515)"
  
- title: "Student Volunteer"
  content: "CHI - [2023](https://chi2023.acm.org/); C&C - [2023](https://cc.acm.org/2023/); CSCW - [2023](https://cscw.acm.org/2023/)"
