- title: "Program Committee"
  content: "IUI 2026"

- title: "Conference and Journal Reviewing"
  content: "DL4C Workshop (2023); In2Writing Workshop (2024, 2025); C&C (2025); UIST (2025); DIS (2025); CHI (2024, 2025, 2026); ICSE (2026); ASE; SMASH (2025)"
  
- title: "Student Volunteer"
  content: "CHI 2023; C&C 2023; CSCW 2023"
